home/urls.py
from django.urls import path

from . import views
app_name='home'
urlpatterns = [
   #path to function decide if user or admin
   path('homepage',views.homepage,name='homepage'),
   #path admin action(render) ==admin only
   path('home',views.create_profile,name='home'),
   #path to profile update page(render) ==admin only
   path('profileupdate/<uuid:unique_id>',views.profileupdate,name='profileupdate'),
   #path to add visiting page that pass profile uuid(render) ==admin only
   path('addvisiting/<uuid:unique_id>',views.addvisiting,name='addvisiting'),
   #path to addvisiting page to remove visiting pass visiting uuid(render) ==admin only
   path('delete_visitng/<uuid:unique_id>',views.delete_visitng,name='deletevisitng'),
   #path to delete image from visiting by uuid of image ==admin only
   path('deleteimage/<uuid:unique_id>',views.deleteimage,name='deleteimage'),
   #path to upload page images(render) ==admin
   path('uploadimages/<uuid:unique_id>',views.uploadimages,name='uploadimages'),
   #path to function that return list of (json) all visiting of profile login  ==user
   path('homeuser',views.homeuser,name='homeuser'),
   #path to function that return all image of visiting of profile by uuid of visiting login  Response(Json)  ==user
   path('image_visiting/<uuid:unique_id>',views.image_visiting,name='image_visiting'),


   
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
   
    
    path('home/',include('home.urls',namespace='home')),
  
    
]
urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django import forms
from django.db import models
from datetime import datetime
import uuid
from accounts.models import *
from django.utils.timezone import now

   
class Visiting(models.Model):
      '''
      model visiting that contain profile uuid 
      '''
      unique_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
      profile=models.ForeignKey(Profile,max_length=100,related_name="visiting",on_delete=models.CASCADE)
      created=models.DateTimeField(default=now, editable=True)
      
      updated=models.DateTimeField(auto_now=True)
      def __str__(self):
            return self.profile.name
      class Meta:
            ordering = ['created']



def impage_upload(instance,filename):
      '''
      function that save image in folder named by [username/year/month/day/name.ext]
      django speed search by number
      '''
      imagename,extension=filename.split(".")
      year=datetime.datetime.now().year
      month=datetime.datetime.now().month
      day=datetime.datetime.now().day

      return '%s/%s/%s/%s/%s.%s'%(str(instance.visiting.profile.mobile),str(year),str(month),str(day),str(imagename),str(extension))
      


class Image_visiting(models.Model):
      '''
      model images that contain visit uuid 
      when delete image from database remove file from forlder

      '''
      unique_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
      visiting=models.ForeignKey(Visiting,max_length=100,related_name="image_visting",on_delete=models.CASCADE)
      img_visiting= models.ImageField(upload_to=impage_upload)
      created=models.DateTimeField(auto_now_add=True, editable=True)
      updated=models.DateTimeField(auto_now=True)
      def __str__(self):
            return self.visiting.profile.name
      class Meta:
            ordering = ['created']
      
      def delete(self, using=None, keep_parents=False):
            self.img_visiting.storage.delete(self.img_visiting.name)
           
            super().delete()


@receiver(pre_save, sender=Image_visiting)
def upload_file_pre_save(sender, instance, **kwargs):
      '''
        signals =>you can upload max 4 images in one visiting
        
      '''
      if Image_visiting.objects.filter(visiting_id=instance.visiting_id).count() >= 4:
          raise forms.ValidationErro('sorry cant upload more than 4')  

  

home/views.py
import random
from django.shortcuts import redirect, render
from django.views.decorators.csrf import csrf_exempt
from rest_framework.views import APIView

from rest_framework.response import Response
from accounts.forms import CreateProfileForm
from accounts.serializer import ProfileSerializers
from accounts.forms import Image_VistingForm
from home.models import Image_visiting
from .serializers import VisitingSerializers,Img_visitingSerializers
from django.contrib.auth.decorators import login_required
from accounts.models import Profile
from accounts.forms import CreateProfileForm, ProfileUpdate
from django.urls import reverse
from rest_framework.decorators import api_view
from accounts.forms import ProfileUpdate
from accounts.models import *
from django.core.paginator import Paginator
from django.db.models import Q
from accounts.forms import VistingForm
from home.models import Visiting
import os
from twilio.rest import Client




#func to route admin and user
@api_view(['GET','POST'])
@csrf_exempt                
def homepage(request):
      if request.user.is_authenticated and request.user.is_superuser:
            return redirect('home:home')


      return redirect('home:homeuser')

#func get all profile in home admin page to do actions delete add .....
def getprofile(request):
            profile=Profile.objects.all().order_by('-created')
            Serializer=ProfileSerializers(profile,many=True)  
            data=Serializer.data
            paginator=Paginator(data,7)
            page_number=request.GET.get('page')
            return paginator.get_page(page_number)

#fun get all visiting of user by id of user
def getvisitng(request,unique_id):
            visiting=Visiting.objects.filter(profile_id=unique_id).order_by('-unique_id')
            Serializer=VisitingSerializers(visiting,many=True)  
            data=Serializer.data
            paginator=Paginator(data,7)
            page_number=request.GET.get('page')
            return paginator.get_page(page_number)

#func find user by phone number or name 
def search_user(request):
            q = request.POST.get('search_query')
            results = Profile.objects.filter(Q(name__icontains=q) | Q(mobile__icontains=q))
            Serializer=ProfileSerializers(results,many=True)  
            data=Serializer.data
            paginator=Paginator(data,7)
            page_number=request.GET.get('page')
            return paginator.get_page(page_number)  
#func get all image of one visiting by id 
def get_user_image_visiting(visiting_id):

    q=Image_visiting.objects.filter(visiting_id=visiting_id)
    serializers=Img_visitingSerializers(q,many=True)
    data=serializers.data
    return data
def sendsms(phone,password):   
    account_sid = 'AC66c89f275dac90f58ea3fd0683ee566f'
    auth_token = 'fc046fb8dc1529a3af584fc5964eb66c'
    client = Client(account_sid, auth_token)
    client.messages \
            .create(
                    body="welcom in omoma clinic your password is : "+str(password),
                    from_='+18482835968',
                    to='+201159087296'
                    )
             
   
#func create profile by name , phone number and autogenrate password 
#before create profile create user contain username=phone number and password=password
#send sms that contain password and link of app in google paly

@login_required(login_url='login')
@api_view(['GET','POST'])
@csrf_exempt
def create_profile(request):
    '''
    #1 function to load all profile in page 
    #2 if method post and contain hidden input name='from_type' and value=adduser
    #3 take request in form 
    #4 if form valid get from form username=mobile,name=name 
    #5,6,7,8 create User with username=mobile and first_name=name ,password auto generated and return form if exception occure
    #9,10,11 create profile mobile=mobile,name=name,and return form if exception occure,
    #12,13 send sms to user contain password,load profiles to dispaly in home page
    #14 if method post and contain hidden input name='from_type' and value=search
    #15 function search profile and display result in home page 
    #16 load home page and dispaly list of profiles,and form create profile
    '''
    try:   
            profiles=getprofile(request)                                                     #1
            if request.method=='POST':
                if request.POST.get('form_type')=='adduser':                                #2
                                    form=CreateProfileForm(request.POST)                    #3
                                    if form.is_valid():  
                                        username = form.cleaned_data.get('mobile')          #4
                                        name= form.cleaned_data.get('name')                 #5
                                        try: 
                                            user=User.objects.create(username=username,first_name=name) #6
                                        except:
                                            form=CreateProfileForm(request.POST)                        #7
                                            
                                        else:
                                            password=str(random.randrange(1111111111,9999999999))    #8
                                            user.set_password(password)
                                            user.save()
                                            try:
                                                profile_create=Profile.objects.create(user=user,name=name,mobile=username) #9
                                            except:
                                                form=CreateProfileForm(request.POST)                                       #10
                                            else:           
                                                profile_create.save()                                                      #11
                                                sendsms(phone=username,password=password)
                                                profiles=getprofile(request)                                               #12
                                                return render(request,'home.html',{'form1':form,'profiles':profiles})      #13      
                                    else:
                                        form=CreateProfileForm(request.POST)              #13
                elif request.POST.get('form_type')=='search':                             #14
                   form=CreateProfileForm()                                               #15
                   profiles=search_user(request)
                else:
                 form=CreateProfileForm()   
            else:
               form=CreateProfileForm()    
    except :
           form=CreateProfileForm()
    else:
        return render(request,'home.html',{'form1':form,'profiles':profiles})     #16 



@login_required(login_url='login')
@api_view(['GET','POST'])
@csrf_exempt
def profileupdate(request,unique_id):
    '''
    #1,2 check user and profile exists
    #3,4,5,6,7 if user and profile exsits and form is valid save updating data and return the same page
    #8,9 if is not valid load same page with old data profile
    # if user no exists return home page  
    '''
    try:
       profile=Profile.objects.get(unique_id=unique_id)                             #1
       user=User.objects.get(id=profile.user_id)                                    #2
    except:
        return redirect('home:home')
    else:                                                                           #3
            if profile and user:  
                if request.method=='POST':                                          #4
                        
                        profileform =ProfileUpdate(request.POST,instance=profile )  #5
                        if profileform.is_valid():
                                
                                profileform.save()                                  #6
                            
                                return redirect('home:profileupdate',unique_id=unique_id) #7
                        else:
                        
                            profileform = ProfileUpdate(instance=profile)                #8
                else :
                    profileform = ProfileUpdate(instance=profile)                       #9
                    return render(request,'profile_update.html',{'profileform':profileform})#10

            else:
               return redirect('home:home')                                                  #11



@login_required(login_url='login')  
@api_view(['GET','POST'])
@csrf_exempt
def addvisiting(request,unique_id):
    '''
       #1 Verifies that this item already exists  in database 
       #2 exception occure redirect to home page 
       #3 load all visting  to show in page
       #3,4 if visting existis and method post
       #4,6 form takes requset post and check method type ,and valid 
       #7,8,9 try to adding visting ,if exception occure form still empty in page at the end show all visiting image in page 
       #10,11 if item success adding load images show redirect in page contian item added and show form adding in page
        
    '''
    try:
       pro=Profile.objects.get(unique_id=unique_id)                                    #1
    except:
           return redirect('home:home')                                                #2
    else: 
        if pro:      
                visiting_user= getvisitng(request,unique_id)                           #3
                form=VistingForm(request.POST)                                         #4
                if request.method=='POST':                                             #5
                    if form.is_valid():                                                #6
                            

home/templates/add_visiting.html
{% extends 'basehome.html' %}
{% load bootstrap4 %}

    {% block body %}

    <!--div row  -->
    <div class='row contentdiv'>
         
                                              <div class="col-4">
                                               <form method="POST" >
                                                {% csrf_token %}
                                                <div class='row'>
											   <input type="date" name ='created'  required  class="form-control">
                                                </div>
												<div class=' row container'>
                                                {% buttons %}
                                                    
                                                    <button class="boxed-btn3 w-100" type="submit">ADD NEW VISITING</button>
                                                {% endbuttons %}
												</div>
                                               </form>
                                               </div>
                                               	<div class="col-7">
														<table class=" table table-striped table-sm">
														  <thead>
																<tr>
																	
																	<th scope="col">Date Visting</th>
                                                                    <th scope="col">update</th>
                                                                    <th scope="col">Delete</th>
																
																</tr>
															</thead>
															<tbody>
																{%for visit in visting%}
																  <tr>
																	   
																
																	   <td>{{visit.created}}</td>
																	   <td>

                                      <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><a href='{% url 'home:deletevisitng' unique_id=visit.unique_id  %}'>Delete Visting</a></button>
	
                                                                       </td>

                                                                        <td>
																	    <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><a href='{% url 'home:uploadimages' unique_id=visit.unique_id  %}'>Add Images</a></button>
											                           </td>
																	
																	  </tr>
																{% endfor%}
															</tbody>
														</table>
												</div>
               
    </div>
         

    
    {% endblock body %}	

home/templates/basehome.html
{% load static %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"  >
	
    <link rel="stylesheet" href="{% static 'js/jquery.min.js' %}">
  
       <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/gijgo.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/slicknav.css' %}">
    
    <link rel="stylesheet" href="{% static 'css/create.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
      
</head>
       <body>

    	      <!-- div container page-->
							<div class="container-fluid contentdiv page-container">

<!--###############################header#########################################################-->
								<div class="row ">
									<div class="col">
									    <!-- navbar contain button logout -->
										<nav class="navbar navbar-light bg-light justify-content-between">
													<a class="navbar-brand">Omama clinic tech</a>
													<form class="form-inline" >
															{% if user.is_authenticated %}
															     <p>  Hi {{ user.first_name}} !  </p>
															{% endif %}		
														<button class="btn btn-outline-success my-2 my-sm-0" type="submit"><a href='{% url 'logout' %}'>Logout</a></button>
													</form>
											</nav>
									</div>
								</div>
       
<!--########################### ####content#########################################################-->
                     {% block body %}

                     {% endblock body %}


<!--########################### ####footer#########################################################-->
				            
											<footer class="bg-light text-center text-lg-start page-footer">
														<!-- Copyright -->
													<div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
															© 2021 Copyright:
															<a class="text-dark" href="{ url'create'}">omomaclinctech.com</a>
													</div>
														<!-- Copyright -->
											</footer>
									 
				
<!--############################### end container#########################################################-->
				</div> <!--end div container-->    
       <script src="{% static  'js/jquery-3.2.1.slim.min.js' %}" ></script>
			<script src="{% static 'js/popper.min.js' %}" ></script>
			<script src="{% static 'js/bootstrap.min.js' %}" ></script>
   </body>
</html>

home/templates/home.html
	{% extends 'basehome.html' %}
{% load bootstrap4 %}

    {% block body %}		            
			
<!--###############################start content#########################################################-->
				               <div class="row contentdiv ">
							   <!--***************************col 1 form****************************************-->
									<div class="col-5">
									 <!--error of request form adding -->
										{% if form1.errors %}
										    {% for key,value in form1.errors.items%}
										         {% for item in value %}
													<p class="text-danger">{{item}}</p>
												 {% endfor %}
										    {% endfor %}
										{% endif %}	
										 <!--form adding new user-->
											<div class="row">
													<div class="col">
															<div class="card">
																	<div class="card-body">
																			<div class="d-flex justify-content-center form_container">
																				
																				<form method="POST" action="">
																						{% csrf_token %}
																						<div class="input-group mb-3">
																								<div class="input-group-append">
																									<span class="input-group-text"><i class="fas fa-user"></i></span>
																								</div>
																								<input type="text" name="mobile" placeholder="Phone Number "  class="form-control" required>
																						</div>

																						<div class="input-group mb-2">
																								<div class="input-group-append">
																									<span class="input-group-text"><i class="fas fa-key"></i></span>
																								</div>
																								
																								<input type="text" name="name" placeholder="Full Name" class="form-control" required >
																						</div>

																						<div class="d-flex justify-content-center mt-3 login_container">
																							
																						        <input type="hidden" name="form_type" value="adduser">
																						        <input class="btn login_btn" type="submit" value="ADDING USER">					
																					  </div>
																				</form>
																			</div>
																	</div>		
															</div>
													</div>
												</div>
									</div>
							 <!--***************************col 2 table and nav search bar ****************************************-->
									<div class="col-7">
										<div class="container-fluid  justify-content-start">
											<div class="row"> 
												<div class="col">
												       <!-- error nav serach user-->
														{% if profiles.errors %}
															{% for key,value in profiles.errors.items%}
																	{% for item in value %}
																	   <p class="text-danger">  {{item}}</p>
																	{% endfor %}
															{% endfor %}
														{% endif %}
														<!-- form serach serach user-->
														<div class='box nav1 justify-content-between'>
														    <nav class="navbar navbar-light bg-light justify-content-between">
																  <a class="navbar-brand">Last Users Added</a>
																  <form class="form-inline" method='POST'>
																		{% csrf_token %}
																		<input class="form-control mr-sm-2" type="search"name='search_query' placeholder="Enter name or phone" aria-label="Search">
																		<input type="hidden" name="form_type" value="search">
																		<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
																	</form>
															</nav>
														</div>
	
												</div>
											</div>
											 <!--table show user lists-->
											<div class="row"> 
												<div class="col">
														<table class=" table table-striped table-sm">
														  <thead>
																<tr>
																	<th scope="col">name</th>
																	<th scope="col">phone number</th>
																	<th scope="col">update</th>
																	<th scope="col">add visitng</th>
																</tr>
															</thead>
															<tbody>
																{%for pro in profiles%}
																  <tr>
																	   
																	   <td>{{pro.name}}</td>
																	   <td>{{pro.mobile}}</td>
																	   <td>
																	<button class="btn btn-outline-success my-2 my-sm-0" type="submit"><a href='{% url 'home:profileupdate' unique_id=pro.unique_id  %}'>Update</a></button>
											                           </td>
																	      <td>
																	<button class="btn btn-outline-success my-2 my-sm-0" type="submit"><a href='{% url 'home:addvisiting' unique_id=pro.unique_id  %}'>Add Visitng</a></button>
											                           </td>
																	  </tr>
																{% endfor%}
															</tbody>
														</table>
												</div>
											</div>
											 <!--pagination of user profiles lists-->			  
											{% if profiles.has_other_pages %}   
													<div class="row">
													      <div class="col-lg-12">
													           <div class="pagination_wrap">
																	<ul>
																		
																		{% if profiles.has_previous %}
																			<li><a href="?page={{profiles.previous_page_number}}"> <i class="ti-angle-left"></i> </a></li>
																		{% endif %}

																		{% for i in profiles.paginator.page_range %}
																			<li><a href="?page={{i}}"><span>{{i}}</span></a></li>
																		{% endfor %}
																		
																		{% if profiles.has_next %}
																			<li><a href="?page={{profiles.next_page_number}}"> <i class="ti-angle-right"></i> </a></li>
																		{% endif %}
																	</ul>
												            	</div>
												           </div>
											        </div>
											{% endif %}
															
										</div>
									</div>
				                </div> <!--end div container contentdiv-->
		 {% endblock body %}	

home/templates/profile_update.html
{% extends 'basehome.html' %}
{% load bootstrap4 %}

    {% block body %}

    <!--div row  -->
    <div class='row contentdiv'>
         
   
                    <div class="container">
                        <div class=" card width: 18rem;">
                                    <h3 class="card-title justify-content-center">Edit Profile</h3>
                                    <div class="col-10 mx-auto card-body">
                                       
                                            
                                            <form method="POST"  >
                                                {% csrf_token %}
                                            
                                                {% bootstrap_form profileform %}
                                                 <div>
                                                 <label for="exampleInputPassword1">Date pregnant</label>
											       <input type="date" name ='date_pregnant'   class="form-control">
                                                </div>
                                                {% buttons %}
                                                    
                                                    <button class="boxed-btn3 w-100" type="submit">Save Update</button>
                                                {% endbuttons %}
                                            </form>
                                        </div>
                           </div>
                 
                        </div>
               
    </div>
         

    
    {% endblock body %}	

home/templates/upload.html
{% extends 'basehome.html' %}
{% load bootstrap4 %}
{% load static %}

           {% block body %}
                <div class='row contentdiv'>
                    <div class="col-5">
                        <div class=" card width: 18rem;">
                                   <div class='card-title justify-content-end"'>  
                                     <h3 class="card-title justify-content-end"> Upload images</h3>
                                    </div>
                                    <div class="col-10 mx-auto card-body">
                                            {% if form.errors %}
                                                  {% for field in form %}
                                                      {% for error in field.errors %} 
                                                          <div class="alert alert-danger">
                                                              <strong>{{ error|escape }}</strong>
                                                          </div>
                                                      {% endfor %}
                                                  {% endfor %}
                                            {% endif %} 
                                            <form method="POST" enctype="multipart/form-data">
                                                  {% csrf_token %}
                                                  <input type="file" id="files" name="img_visiting" multiple  required  class="form-control"> 
                                                  <button class="boxed-btn3 w-100" type="submit">uplaod Images</button>
                                            </form>
                                    </div>
                        </div>
                    </div>
                    <div class='col-7'>
                                <div class=" card width: 18rem;">
                                     {% for imagesrc in img  %}
                                          <div class="col-10 mx-auto card-body " >    
                                              <a href='{{imagesrc.img_visiting}}'>  
                                              <img src="{{imagesrc.img_visiting}}" class="img-fluid" onerror="this.onerror=null; this.src='{% static 'error1.png' %}'" alt="image"></a>
                                              <a href='{% url 'home:deleteimage' unique_id=imagesrc.unique_id  %}'>   <button type="button" class="btn btn-danger">Delete</button>
                                          </div>
                                     {% endfor %}
                                     
                                     
                                </div>
                    </div>
               </div>
           {% endblock body %}	